### ISSUE TITLE
Implement "edit" link for review

### ISSUE THREAD

**Issue by gleemie** [turkopticon/turkopticon-rails-app#11]
Each review authored by the logged in user should have an edit link next to "comment" so they can go back and edit it if there's a typo or they need to update. 
(This would be very helpful for my usability run throughs because I entered some reviews and misclicked something that makes the review confusing.)

**Comment by zihel** [comment]
There's an edit link on the /reviews page. When a user clicks the 'my reviews' link on the user bar in the header it'll load up all reviews they've made. They can find an edit link there, but I'll add the edit link into the /requesters page as well for convenience.
