### ISSUE TITLE
Search on requester ID is not finding records

### ISSUE THREAD

**Issue by kimadagem** [turkopticon/turkopticon-rails-app#25]
I was trying to update some reviews I posted yesterday and used my usual procedure (from the original site), which is to search on requester ID, but there were no results. I experimented with a requester name instead and that worked, but requester names can change. I don't know if the search is set up to accept historical names but for me the ID is more reliable because it's not subject to changes or misspellings. Maybe there's a better way to update than a search, like maybe with the new script (which I haven't figured out how to use yet), and I'm probably one of the few people who actually has a record of the requester ID, but since the original site is set up to search both with IDs and names I think it would be helpful if the new site could do the same. Thanks.

**Comment by zihel** [comment]
It searches across both current name and all past names so name changes should not be an issue. As you said, most users will be searching by name, but I'll increase the search domain to include IDs as well.
