### ISSUE TITLE
Review text is displaying "n/a" instead of what I wrote

### ISSUE THREAD

**Issue by kimadagem** [turkopticon/turkopticon-rails-app#26]
I notice that reviews from some other workers are also doing this. Maybe they didn't put anything in that field but I did - I added the date I did the hit - and none of the reviews I've posted today are displaying that (yesterday's are fine). I experimented with 2 and also 3 lines of text instead of just 1 but that didn't make a difference. I really would like to include the date I did the hit so I'll stop adding reviews for now.

**Comment by zihel** [comment]
Thanks for the report! I know what causing this. A fix will be out shortly.
