### ISSUE TITLE
Text box on requester summary (aggregate) page is not including line breaks

### ISSUE THREAD

**Issue by kimadagem** [turkopticon/turkopticon-rails-app#28]

**Comment by zihel** [comment]
I'm not really sure what you mean by this. I'm assuming it's regarding the rendering of user-supplied formatting and new lines in the 'additional information/context' section of the review?

**Comment by kimadagem** [comment]
I'm sorry, I should have included screenshots. Here's what I'm talking 
about:

The way I wrote & formatted that field:
![to2 line break issue 1](https://cloud.githubusercontent.com/assets/26679556/24428618/0b33e6d8-13dd-11e7-904c-ded4b51fb104.jpg)

And here is how it displays:
![to2 line break issue 2](https://cloud.githubusercontent.com/assets/26679556/24428639/1620a18a-13dd-11e7-880c-f5799aced47f.jpg)

Someone else has noticed it:
![to2 line break issue 3](https://cloud.githubusercontent.com/assets/26679556/24428656/1e24926a-13dd-11e7-9355-63110404ddba.jpg)

I can't see the original formatting on that last one (maybe it shows 
only in edit mode, which I can't access) but based on the comment I'm 
guessing it wasn't written that way.

I hope that makes more sense.

**Comment by zihel** [comment]
All HTML formatting is stripped from emails and converted to plain text when you reply to github via email. This means your images still aren't showing. 

Also, using the web interface, github supports markdown so you can use the same formatting techniques you use on reddit, with the addition of inline images. To attach an image use `![](url-to-image)`. It's similar to links but has an exclamation point in front.

**Comment by NurseRachet** [comment]
Kimadagem mentioned this in a couple of her reviews - I'm confident she is referring to the inability to create paragraphs. When writing a review, the creation of line breaks to separate text into paragraphs is allowed, but the line breaks are not translated into the posted review. Because of this, paragraphs are blurred into one giant wall of continuous text, which makes lengthy reviews visually difficult to read.

Hope this helps.

**Comment by kimadagem** [comment]
Thank you, NurseRatchet. Yes, that's what I meant; you just said it better.

**Comment by NurseRachet** [comment]
You are most welcome kimadagem. It was rather difficult to describe this
issue for some reason. I kept having to rephrase my text to make it
understandable.
