### ISSUE TITLE
Text from write-in box for "Do you recommend this" field is not displaying on requester page

### ISSUE THREAD

**Issue by kimadagem** [turkopticon/turkopticon-rails-app#29]
This appears to be an issue with the "Broken" field also. If there is no explanation in the "additional information" field no one will know why the hit isn't recommended or how it's broken. (I can do screenshots if needed but if you check my reviews for 3/30 you'll find two examples.)

**Comment by zihel** [comment]
The explanations are currently shown when you hover over the tag. I've received similar feedback on this though, and I'll change how they're displayed soon.
