### ISSUE TITLE
Reviews can no longer be edited

### ISSUE THREAD

**Issue by NurseRachet** [turkopticon/turkopticon-rails-app#35]
The edit option previously existed, but no longer does. Reviews can not be edited anymore.

**Comment by zihel** [comment]
I don't think that's true. The user below edited ~2 hours ago.
![image](https://cloud.githubusercontent.com/assets/19792552/24736940/0d952dce-1a59-11e7-90d3-f9d3fc28ad4b.png)

Please check either under the requester or in the review footer. It'll be in the review footer when browsing by requester, and under the requester when browsing by review
![image](https://cloud.githubusercontent.com/assets/19792552/24737086/1a42bd24-1a5a-11e7-92a7-b04c6f7e29b1.png)
![image](https://cloud.githubusercontent.com/assets/19792552/24737062/fc9b9a0c-1a59-11e7-97af-d4b54927a439.png)

**Comment by NurseRachet** [comment]
Ahhh, I see. The review command was moved from the review footer, and is now below
the requester name. Sorry 'bout that.

**Comment by NurseRachet** [comment]
I no longer am seeing the edit command on the review footer when viewing all reviews, or reviews by a single reviewer. Wasn't this there before, or was this an intended change?

![image](https://cloud.githubusercontent.com/assets/20234023/24739398/5fc370b2-1a61-11e7-90a8-e319e7bf272a.png)

**Comment by zihel** [comment]
You may be mis-remembering; the edit link has never been in the review footer. The [original mockups](https://github.com/turkopticon/devel-2016/tree/master/mockups) from Lilly places the edit link under the requester. It was expected that users would edit from their 'my reviews' page. It wasn't until we saw that users were confused about how to edit reviews during our alpha run-throughs that we realized this was not great design. In response, we decided to add edit links everywhere that a user might run into one of their own reviews. 

The link in the footer only appears if the requester (and by extension, the edit link under the requester) is not present.
