### ISSUE TITLE
(Script) Add link for new review to hit page after hit has been accepted

### ISSUE THREAD

**Issue by kimadagem** [turkopticon/turkopticon-rails-app#38]
I'm not sure this is the right place for this, but I'm not sure where else to ask.

I just had to return a hit that was turning out to be too long. The requester is new (no reviews on either TO site) and the the link on the hit page disappeared once I'd accepted the hit. I had to use the "new review" page, which took time because I had to locate all the needed data for the fields. I don't know if it's possible to keep the link there after the hit is accepted, but if it is that would save time; I had to copy/paste the data for the fields from several different sources.

**Comment by zihel** [comment]
please use the repository for the script [turkopticon/turkoptiscript](https://github.com/turkopticon/turkoptiscript)

I've already migrated this over: turkopticon/turkoptiscript#2
