### ISSUE TITLE
Unable to Login to TO Beta Site!!

### ISSUE THREAD

**Issue by CM3Turk** [turkopticon/turkopticon-rails-app#43]
I have been unable to login to the new Turkopticon Beta site with my account email and password. I have tried logging in while logged in and logged out of the original Turkopticon site. I do not have issues logging into the original site. Do I need to make a new login with my current account info? It tells me that my username/password is invalid.

**Comment by zihel** [comment]
I've verified that your account exists in the database. You shouldn't have any issues. Can you try resetting your password? Do you still have access to that email?

**Comment by CM3Turk** [comment]
@zihel,
I have tried resetting my password as you recommended, but it still does not work. This is my main email and have access to it daily. When I try to login, it says "Sorry, invalid username/password combination".
I have tried logging while I am logged in and out of the old site. I have no clue what the problem could be.

**Comment by zihel** [comment]
What message did you receive when you reset your password? Did you get confirmation that a reset email was sent or did you get a message stating that the user does not exist?

**Comment by CM3Turk** [comment]
After I reset my password, I got the message that a confirmation email was sent. I received the confirmation email immediately and was able to login to the old site with my new password, but I am still unable to login to the beta site.

**Comment by zihel** [comment]
I think there's a misunderstanding here. You need to [reset your password](https://turkopticon.info/account/password_reset/new) on the new site. Resetting your password on the legacy site is not going to resolve anything related to turkopticon.info. The two sites maintain a separation of databases.

**Comment by CM3Turk** [comment]
How am I able to reset my password on the new site if I am unable to login to the new site to go into my account settings to change/reset my password? Unless you mean that I should choose the "forgot my password" option on the new site and reset it that way ... I am sorry if I misunderstood you ...

**Comment by CM3Turk** [comment]
Unless you are instructing me to choose the "forgot my password" option on the new site and reset it that way .... ?

**Comment by zihel** [comment]
Yes. That is exactly what I'm suggesting you do.

**Comment by CM3Turk** [comment]
YES! PROBLEM SOLVED! Thank you for staying on top of my issue and being so prompt and helpful in your responses! I will be using the new site for now on!
