### ISSUE TITLE
ability to pass review data in url, integrate with turkoscript

### ISSUE THREAD

**Issue by toutils** [turkopticon/turkopticon-rails-app#44]
A feature suggestion, it would be nice if you could pass data to https://turkopticon.info/reviews/new
to prefill some of the fields. This would allow turkoscript or any other script to stick a review button on
https://www.mturk.com/mturk/continue

You click the button, it takes you to the new review page on turkopticon.info, with the hit title, requester name, and pay pre-filled. Turkoscript or some other script might even track completion time and prefill that too.

**Comment by zihel** [comment]
I don't understand. This already exists and the script already pre-fills those exact fields.

**Comment by toutils** [comment]
I just noticed that thanks, the site's already capable of this and turkoscript does it on
https://www.mturk.com/mturk/myhits
The only feature suggestion then would be add turkoscript to 
https://www.mturk.com/mturk/continue
prefilling the fields that it has.

I'm going to close the issue though, it would belong on turkoscript anyway and any other script can do this.
