### ISSUE TITLE
500 error when adding review of new requester

### ISSUE THREAD

**Issue by toddwc** [turkopticon/turkopticon-rails-app#49]
Tried to contribute my first review, of a requester who is not already listed in 2.0, but I received a 500 error after submitting:

> Error 500: Internal Server Error :-(
> 
> If you are getting this message around 1:30 AM Pacific Time after typing something into the search box, the search index is probably being updated. Search does not work while this is happening. Try again in a few minutes.
> 
> Otherwise, something else went wrong. Please post to turkopticon-discuss or email turkopticon@differenceengines.com. Thanks!

I went back and looked for errors and tried a second time, but I received the same error again.

**Comment by zihel** [comment]
What exactly are you doing? I cannot reproduce this and I see others are adding reviews for new requesters just fine.

**Comment by toddwc** [comment]
Filling in all of the info on this page and then submitting it:

https://turkopticon.info/reviews/new

Is there another way of doing it?

**Comment by toddwc** [comment]
I turned off uBlock Origin and all is now well. Sorry.

**Comment by zihel** [comment]
Do you know what the block rule in UBO was that was affecting this?

**Comment by toddwc** [comment]
It appears to be `||google-analytics.com^` in [Peter Lowe’s Ad and tracking server list](https://pgl.yoyo.org/adservers/).


![screenshot - 4_15_2017 3_49_15 am](https://cloud.githubusercontent.com/assets/167818/25061911/8bc8f9be-218e-11e7-9c41-f3110347ed88.png)

![screenshot - 4_15_2017 3_50_55 am](https://cloud.githubusercontent.com/assets/167818/25061935/6fa8e130-218f-11e7-9469-c47407e89a21.png)

![screenshot - 4_15_2017 3_17_51 am](https://cloud.githubusercontent.com/assets/167818/25061806/40e06e20-218c-11e7-8951-1b01450254e6.png)

**Comment by zihel** [comment]
That's strange. Google analytics is not required and has literally no influence whatsoever on operations. I'll have to investigate further. You may continue blocking it if you'd like. Let me know if you run into it again.

Thanks

**Comment by toddwc** [comment]
Blocking it apparently breaks a lot of sites, requiring the Easy Privacy list to whitelist it for a number of domains.

There's a uBlock Origin experimental filter that redirects those google-analytics.com calls to a neutered version of analytics.js. I've enabled it to see what happens.
