### ISSUE TITLE
Old Reviews and Updating on Them ... 

### ISSUE THREAD

**Issue by CM3Turk** [turkopticon/turkopticon-rails-app#51]
I have questions about the old review pool. Are they going to be added to the new site in the future and how should I properly update about a requester for HITS I previously reviewed on the legacy site. For example, receiving a bonus on a HIT that I already reviewed on or finally hearing from a requester about a certain HIT and so on ?

**Comment by zihel** [comment]
No. The reviews on legacy are incompatible with the new site and cannot be automatically migrated over. There are, however, some users that are porting over some of their old reviews to the new system. You're welcome to do that as well. 

After you make a review you can update it with new information by editing just like before.

**Comment by CM3Turk** [comment]
Great! I will start porting over my old reviews if that helps, I will just date them accordingly.
