### ISSUE TITLE
Porting Old Reviews to New Site ..... 

### ISSUE THREAD

**Issue by CM3Turk** [turkopticon/turkopticon-rails-app#53]
I have a question about how to go about porting over the old reviews to the new site while keeping the integrity of the site in check. Some reviews contain comments, flags, and moderator inputs, all of which are vital to the foundation of TO. How should we properly go about adding old reviews which may contain comments, flags and so on?

**Comment by zihel** [comment]
Just use your best judgement. Some flags are no longer relevant, but if a review has a valid flag on it, fix the issue while porting it over. With comments, if it's actually relevant then you can sum it up succinctly in the provided textbox for additional context. Don't just copy/paste the entire comment thread. Again, use your best judgement; no one wants to be greeted with a giant wall of text when trying to evaluate a requester.
