### ISSUE TITLE
"Approval time in hours" field isn't accepting decimals/fractions

### ISSUE THREAD

**Issue by kimadagem** [turkopticon/turkopticon-rails-app#55]
I've used them there before because I've seen the results show as "15 minutes" etc., but that's not working now; I wasn't able to use anything less than a whole number, even after trying several variations (".25," "0.25," ".3," "1/4"). I ending up adding a sentence in the text field so I could be more specific about the actual time.

**Comment by CM3Turk** [comment]
I also was thinking about this too ... I have HITS that approve in minutes.
