### ISSUE TITLE
Text in "Time to Approve" field

### ISSUE THREAD

**Issue by kimadagem** [turkopticon/turkopticon-rails-app#58]
I see that if the time is in hours then "hrs" will display, but if it's in days there's nothing but a number, which could be confusing to the reader. If there's a way to add "days" to that field I think that would be clearer. Thanks.

**Comment by zihel** [comment]
Thanks, this is the same issue as #57. Unfortunately it's not worded in a way that really makes sense to anyone else, but this is the exact issue that describes.

Closing this as duplicate.
