### ISSUE TITLE
Automatic login

### ISSUE THREAD

**Issue by kimadagem** [turkopticon/turkopticon-rails-app#65]
Someone brought this up on the thread I posted on Reddit so I've decided to add an issue about it.

I have TO1 set to keep my login so I don't have to redo that every day when I start work; I'm just using a cookie manager but there may be other ways (this is not something I know much about). I set the cookie manager the same way for the new site but it isn't working; for whatever reason, my login isn't being saved so I have to redo it every day. It's been a minor annoyance but nothing I can't handle so I wasn't going to bring it up here. But it seems that this is holding up at least the person who commented about it on that thread, and there may be more who haven't said anything.

Is there a way to keep people logged in to the new site so they don't have to redo it? Is this something that has to be built in to the site or is there an external way that I can use, and maybe pass along to others like the Reddit commenter?

**Comment by zihel** [comment]
Whoops, somehow missed this in my alert notifications. Maintaining logged in status from legacy TO to new TO is not possible. For security, no site can read the cookies of a different domain. The best we can do is synchronize accounts from legacy to the new database (which we already do), but they'd still have to log in.
