### ISSUE TITLE
Google is blocking access to site

### ISSUE THREAD

**Issue by toddwc** [turkopticon/turkopticon-rails-app#67]
Chrome is blocking access to site because it says the certificate expired yesterday.

![screenshot - 6_3_2017 3_28_29 pm](https://cloud.githubusercontent.com/assets/167818/26756483/5cfa2068-4871-11e7-8c14-1130c8bb799b.png)

**Comment by kimadagem** [comment]
I just got the same message from Firefox:

![to2 connection not secure message](https://cloud.githubusercontent.com/assets/26679556/26757443/4021bdee-4889-11e7-83e6-dd5ddd89fb3b.jpg)

**Comment by zihel** [comment]
Thanks for letting me know.  The SSL certificate has now been renewed.

**Comment by toddwc** [comment]
Thanks for the quick fix!

**Comment by toddwc** [comment]
Same issue again.

![screenshot - 9_1_2017 6_36_32 pm](https://user-images.githubusercontent.com/167818/29991309-b2e2c764-8f52-11e7-904e-89ce011f7732.png)

**Comment by zihel** [comment]
fixed
