### ISSUE TITLE
Time to Step Aside

### ISSUE THREAD

**Issue by toddwc** [turkopticon/turkopticon-rails-app#74]
This is the third time I've told you about an invalid security certificate. 

It's great that you took on this project, but you should step aside and hand this over to someone else.

**Comment by zihel** [comment]
I was never actually meant to completely take over. Though I do apologize for the annoyance of the expired certificates. It's definitely something that could have been easily prevented. I've set up a cron job to have it be renewed automatically from now on. This should hopefully not be an issue anymore.
